Repository qlik-oss/sense-installer, pull requests merged in 2020-03, with the labels that each got.

#184 Command `qliksense config` fixed, unit tests added
  cmd/qliksense/config.go
  cmd/qliksense/root.go
  go.mod
  go.sum
  pkg/api/apis.go
  pkg/api/encryption.go
  pkg/api/encryption_test.go
  pkg/api/utils.go
  pkg/qliksense/context_configs.go
  pkg/qliksense/context_configs_test.go
Labels: kind/enhancement

#185 Will not display error message twice
  README.md
  action_config.md
  cmd/qliksense/context.go
  pkg/api/utils.go
Labels: kind/bug

#188 fixed base64 decode logic in one spot, updated tests
  pkg/api/apis.go
  pkg/api/kubectl.go
  pkg/qliksense/config.go
  pkg/qliksense/context_configs.go
  pkg/qliksense/context_configs_test.go
  pkg/qliksense/install.go
Labels: kind/bug

#234 Port preflight into sense-installer
  cmd/qliksense/config.go
  cmd/qliksense/preflight.go
  cmd/qliksense/root.go
  go.mod
  pkg/api/kubectl.go
  pkg/api/kubectl_test.go
  pkg/api/utils.go
  pkg/qliksense/preflight_checks.go
  pkg/qliksense/preflight_checks_test.go
Labels: kind/enhancement

#237 Port preflight
  docs/concepts.md
  pkg/api/kubectl.go
  pkg/qliksense/preflight_checks.go
Labels: kind/enhancement

#240 Preflight k8s version check
  cmd/qliksense/preflight.go
  cmd/qliksense/root.go
  docs/concepts.md
  docs/preflight_checks.md
  mkdocs.yml
  pkg/preflight/all_checks.go
  pkg/preflight/dns_check.go
  pkg/preflight/preflight_utils.go
  pkg/preflight/preflight_utils_test.go
  pkg/preflight/version_check.go
Labels: kind/enhancement

#230 Support setting any attribute in Spec (through CR Spec Validation)
  pkg/qliksense/context_configs.go
  pkg/qliksense/context_configs_test.go
Labels: dont merge

#250 Preflight win error
  pkg/preflight/dns_check.go
  pkg/preflight/preflight_utils.go
Labels: kind/bug

#263 troubleshoot-preflight cleaned up and reworked
  .gitignore
  cmd/qliksense/preflight.go
  docs/preflight_checks.md
  go.mod
  pkg/preflight/all_checks.go
  pkg/preflight/dns_check.go
  pkg/preflight/preflight_utils.go
  pkg/preflight/preflight_utils_test.go
  pkg/preflight/version_check.go
Labels: kind/enhancement
