Repository qlik-oss/sense-installer, pull requests merged in 2020-02, with the labels that each got.

#53 Clean porter
  .qliksense/porter-runtime
  .qliksense/porter.exe
  Makefile
  cmd/qliksense/aliases.go
  cmd/qliksense/porter.go
  cmd/qliksense/pull.go
  cmd/qliksense/root.go
  cmd/qliksense/version_checks.go
  pkg/qliksense/docker.go
  pkg/qliksense/porter.go
  pkg/qliksense/qliksense.go
  test/Dockerfile.tmpl
  test/porter.yaml
Labels: kind/enhancement

#55 Config view apply
  cmd/qliksense/config.go
  cmd/qliksense/fetch.go
  cmd/qliksense/install.go
  cmd/qliksense/root.go
  go.mod
  go.sum
  pkg/api/apis.go
  pkg/api/apis_test.go
  pkg/api/kubectl.go
  pkg/api/types.go
  pkg/qliksense/config.go
  pkg/qliksense/fetch.go
  pkg/qliksense/install.go
  pkg/qliksense/operator.go
Labels: kind/enhancement

#62 Fetch install command
  cmd/qliksense/fetch.go
  pkg/api/apis.go
  pkg/api/types.go
  pkg/qliksense/fetch.go
  pkg/qliksense/install.go
Labels: kind/enhancement

#68 Install flags
  cmd/qliksense/install.go
  go.mod
  go.sum
  pkg/qliksense/install.go
Labels: kind/enhancement

#66 Imperative config through cli
  Makefile
  cmd/qliksense/context.go
  cmd/qliksense/root.go
  go.mod
  go.sum
  pkg/api/apis.go
  pkg/qliksense/context_configs.go
Labels: size/L

#70 Imperative config through cli
  pkg/qliksense/context_configs.go
Labels: kind/bug

#75 Imperative config through cli
  pkg/qliksense/context_configs.go
Labels: kind/bug

#78 Add support for rotateKeys and included releaseName as part of CRSpec
  go.mod
  go.sum
  pkg/qliksense/context_configs.go
Labels: kind/enhancement

#79 Fix default install
  cmd/qliksense/fetch.go
  cmd/qliksense/install.go
  cmd/qliksense/root.go
  go.mod
  go.sum
  pkg/qliksense/config.go
  pkg/qliksense/context_configs.go
  pkg/qliksense/fetch.go
  pkg/qliksense/install.go
  pkg/qliksense/qliksense.go
Labels: kind/enhancement

#83 Make file paths portable
  .gitignore
  pkg/qliksense/operator.go
Labels: kind/bug

#82 Make makefile portable
  Makefile
Labels: kind/bug

#81 Support configuration through multiple args
  cmd/qliksense/context.go
  pkg/qliksense/context_configs.go
Labels: kind/enhancement

#114 Encrypt secret in the case: secret=false
  cmd/qliksense/context.go
  cmd/qliksense/root.go
  go.mod
  go.sum
  pkg/api/context_apis.go
  pkg/api/context_apis_test.go
  pkg/api/encryption.go
  pkg/api/encryption_test.go
  pkg/api/types.go
  pkg/api/utils.go
  pkg/qliksense/context_configs.go
  pkg/qliksense/context_configs_test.go
Labels: kind/enhancement

#118 QlikSense config list-contexts
  cmd/qliksense/context.go
  cmd/qliksense/root.go
  pkg/qliksense/context_configs.go
Labels: kind/enhancement

#162 Support for encrypt secret=true
  go.mod
  go.sum
  pkg/api/apis.go
  pkg/api/context_apis.go
  pkg/api/encryption.go
  pkg/api/utils.go
  pkg/qliksense/config.go
  pkg/qliksense/context_configs.go
  pkg/qliksense/install.go
Labels: kind/enhancement

#166 Base64Decode-Decrypt-Encrypt secret value from a given file
  go.mod
  go.sum
  pkg/api/encryption.go
  pkg/qliksense/context_configs.go
Labels: kind/enhancement
